[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rosetta"
version = "1.0.0"
dependencies = [
    "numpy",
    "duckdb",
]
[tool.setuptools]
include-package-data = true
packages = ["rosetta", "rosetta.db"]
[tool.setuptools.package-data]
rosetta = ["db/*"]
